### ISSUE TITLE
Check Motion Guideline from Meta

### ISSUE THREAD

**Issue by neuncreative** [porsche-design-system/digital-design#32]
Scope
---
Check Motion guidelines / philosophy to be in line with digital design motion guide.

Notes
---
- Check on basis of https://github.com/porsche-design-system/digital-design/issues/5
- Frontify: https://brand.porsche.com/document/1060#/motion-concept/intro (Login first)

Acceptance Criteria
---
- [ ] Improvement suggestions documented in Frontify to send/discuss with meta
- [ ] Sync with VMB
- [ ] Sync with Meta
